# Generated by Django 3.1.2 on 2020-10-25 17:45

import bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_acccount',
            name='account_number',
            field=models.IntegerField(default=bank_app.models.random_number),
        ),
    ]
