# Generated by Django 3.1.2 on 2020-10-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_bank_acccount_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_acccount',
            name='balance',
        ),
    ]
