# Generated by Django 3.1.2 on 2020-10-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_remove_bank_acccount_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bank_app.bank_acccount')),
            ],
        ),
    ]
