# Generated by Django 3.1.2 on 2020-10-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
