# Generated by Django 3.1.2 on 2020-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_auto_20201025_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_acccount',
            name='balance',
            field=models.ManyToManyField(blank=True, null=True, to='bank_app.Transaction'),
        ),
    ]
