# Generated by Django 3.1.2 on 2020-10-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_bank_acccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_acccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ManyToManyField(blank=True, null=True, to='bank_app.Transaction'),
        ),
    ]
