# Generated by Django 3.1.2 on 2020-10-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_auto_20201025_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
    ]
