# Generated by Django 3.1.2 on 2020-10-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AddField(
            model_name='bank_acccount',
            name='transactions',
            field=models.ManyToManyField(blank=True, null=True, to='bank_app.Transaction'),
        ),
    ]
