# Generated by Django 3.1.2 on 2020-10-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_auto_20201026_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
    ]
