# Generated by Django 3.1.2 on 2020-10-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0016_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ammount',
        ),
    ]
