# Generated by Django 3.1.2 on 2020-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0017_remove_transaction_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ammount',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
