# Generated by Django 3.1.2 on 2020-10-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0020_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='status',
            new_name='load_permission',
        ),
    ]
