# Generated by Django 3.1.2 on 2020-10-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0024_auto_20201029_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_acccount',
            name='balance',
        ),
    ]
