# Generated by Django 3.1.2 on 2020-10-30 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_app', '0026_auto_20201030_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank_acccount',
            new_name='Account',
        ),
    ]
