# Generated by Django 3.1.2 on 2020-10-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0027_auto_20201030_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='load_permission',
            new_name='loan_permission',
        ),
    ]
