# Generated by Django 3.1.2 on 2020-12-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0029_auto_20201031_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='corresponding_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='b78623a6-da89-4de7-978f-166495e3f40d', max_length=36),
        ),
    ]
