# Generated by Django 3.1.2 on 2020-12-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0030_auto_20201206_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='451382d6-fffc-4ecb-a5b6-c33bec9e3676', max_length=36),
        ),
    ]
