# Generated by Django 3.1.2 on 2020-12-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0032_auto_20201206_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='d7c5604c-a646-4542-b0fc-2320eb1baa46', max_length=36),
        ),
    ]
